# After everything else
# Requires gentoo bash completion package
source /etc/bash/bashrc.d/bash_completion.sh

export PATH="$PATH:$HOME/bin"
export HISTCONTROL="$HISTCONTROL erasedups:ignoreboth"
export HISTSIZE=""
export HISTFILESIZE="-1"


if [[ -e $HOME/.git-prompt.sh ]]; then
	source $HOME/.git-prompt.sh
	export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[01;33m\]$(__git_ps1)\[\033[01;34m\] \$\[\033[00m\] '
	export GIT_PS1_SHOWDIRTYSTATE=1
fi
