set nocompatible
set number
set laststatus=2
set shell=/bin/bash
set packpath+=~/.vim/pack/
set hidden
set title

let g:airline_powerline_fonts = 1
let g:airline_theme='badwolf'
highlight SignColumn ctermbg = 'black'

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_mode_map = { 'passive_filetypes': ['ansible'] }

filetype plugin indent on
syntax enable

set autoindent
set backspace=indent,eol,start
set ttimeout
set ttimeoutlen=50

set incsearch
set hlsearch

" ansible-vim stuff
 au BufRead,BufNewFile */ansible/*.yml set filetype=yaml.ansible
