set nocompatible
set number
set laststatus=2
set shell=/bin/bash

let g:airline_powerline_fonts = 1
let g:airline_theme='badwolf'
highlight SignColumn ctermbg = 'black'

filetype plugin indent on
syntax enable

set autoindent
set backspace=indent,eol,start
set ttimeout
set ttimeoutlen=50

set incsearch
set hlsearch
